services:

  db:
    image: postgres:17.2
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - foodgram-network
  
  backend:
    image: npukojluct/infra-backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - foodgram-network

  frontend:
    build: ../frontend
    container_name: frontend
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      - foodgram-network

  nginx:
    image: nginx:1.25.4-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram-network

volumes:
  postgres_data:
  static_value:
  media_value:

networks:
  foodgram-network:
    driver: bridge